export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN'

export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const REMOVE_USERNAME = 'REMOVE_USERNAME'
