export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN'

export const UPDATE_USERNAME = 'UPDATE_USERNAME'
export const REMOVE_USERNAME = 'REMOVE_USERNAME'

export const UPDATE_EVENT = 'UPDATE_EVENT'

export const UPDATE_INFO = 'UPDATE_INFO'

export const UPDATE_VERSION = 'UPDATE_VERSION'
